# PYTORCH
![](https://upload.wikimedia.org/wikipedia/commons/9/96/Pytorch_logo.png)
## Autograd: Automatic differentiation

- `torch.Tensor` is the central class of the package
- `.requires_grad` as True, it starts to track all operations on it
- Call `.backward()` and have all the gradients computed automatically
- The gradient for this tensor will be accumulated into `.grad`
attribute.

**Tensor**
![](http://deeplizard.com/images/tensor%20operation.png)
Functions supported by Pytorch can be found [here](https://pytorch.org/cppdocs/api/namespace_at.html#functions)

### 1. Create a tensor
PyTorch Tensors are similar in behaviour to NumPy’s arrays.

In [3]:
import torch
import numpy as np

# create a tensor from a list 
x = torch.tensor([[1, 2], [3, 4]])
print(x)

# create a tensor from numpy array
x = np.array([[1, 2], [3, 4]])
x = torch.from_numpy(x)
print(x)

# create a tensor that support gradient calculation
x = torch.tensor([[1.0]], requires_grad=True)
print(x)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])
tensor([[1.]], requires_grad=True)


### 2. Indexing
We can use the NumPy indexing in Tensors:

In [4]:
x[:, 0]             # Can use numpy type indexing
x[:, 0] = -1        # For assignment

### 3. Matrix, vector multiplication

In [5]:
# Dot product of 2 tensors
r = torch.dot(torch.Tensor([4, 2]), torch.Tensor([3, 1])) # 14

# Matrix X vector
# Size 2x4
mat = torch.randn(2, 4)
vec = torch.randn(4)
r = torch.mv(mat, vec)

# Matrix x Matrix
# Size 2x4
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 4)
r = torch.mm(mat1, mat2)

### 4. An example of computing gradients using PyTorch
Define a function over tensors 
$$
f(x) = -2x^2 - 2x - 6
$$

In [6]:
x = torch.tensor([[1.0]], requires_grad=True)
f = -2*x**2 - 2*x - 6
print(f)

tensor([[-10.]], grad_fn=<SubBackward0>)


Compute the derivatives of f with respect to all varaibles having `requires_grad=True`

In [7]:
f.backward()

Print the gradient w.r.t. the input `x`

In [8]:
print(x.grad)

tensor([[-6.]])


Clear the gradient

In [9]:
x.grad.data.zero_()

tensor([[0.]])